name: PR build

env:
  WC_HUGO_VERSION: '0.126.1'
  
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request_target:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout Kaoto
        uses: actions/checkout@v4
        with:
          repository: 'KaotoIO/kaoto'
          path: 'tmp/kaoto'
          fetch-depth: '0'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
      - name: Install Python dependencies
        run: pip3 install PyGithub
          
      - name: Generate Releases and Milestones
        run: python3 getGithubData.py $username $password
        env:
          username: ${{ secrets.API_USER }}
          password: ${{ secrets.API_PASSWORD }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Generate Pagefind search index
        run: npx pagefind --site "public"
      - name: Setup CNAME correctly
        if: always()
        run:  cp CNAME public/CNAME

